/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemamigue;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class MenuMain extends javax.swing.JFrame {

    /**
     * Creates new form MenuMain
     */
    
            //objetos
    Conexion con = new Conexion();
    Connection cn = con.conectar();
    private String atributo = "id";
    
    public MenuMain() {
        initComponents();
        mostraTabla("");
        EnviarNumeros();
        llenarBox();
        //tf_buscar_RC.setVisible(false);
    }
    
            //buscar con el box
    private void buscarTFconBOX(){
        atributo = box_filtro_RC.getSelectedItem().toString();
        mostraTabla(tf_buscar_RC.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_centro = new javax.swing.JTextField();
        tf_zona = new javax.swing.JTextField();
        tf_cpu = new javax.swing.JTextField();
        tf_mouse = new javax.swing.JTextField();
        tf_monitor = new javax.swing.JTextField();
        tf_teclado = new javax.swing.JTextField();
        tf_ups = new javax.swing.JTextField();
        tf_impresora = new javax.swing.JTextField();
        tf_laptop = new javax.swing.JTextField();
        tf_bulto = new javax.swing.JTextField();
        tf_cargador = new javax.swing.JTextField();
        tf_modem = new javax.swing.JTextField();
        tf_internet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_enviar = new javax.swing.JButton();
        btn_tablaOpen = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_tablaOpen2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tf_serial = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        box_filtro_RC = new javax.swing.JComboBox<>();
        tf_buscar_RC = new javax.swing.JTextField();
        bt_buscar_RC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Centro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Zona");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CPU");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mouse");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Monitor");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Teclado");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("UPS");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Impresora");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Laptop");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Bulto");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Cargador");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Moden USB");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Internet");

        tf_centro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_centroActionPerformed(evt);
            }
        });

        tf_zona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_zonaActionPerformed(evt);
            }
        });

        tf_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cpuActionPerformed(evt);
            }
        });

        tf_mouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mouseActionPerformed(evt);
            }
        });

        tf_monitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_monitorActionPerformed(evt);
            }
        });

        tf_teclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tecladoActionPerformed(evt);
            }
        });

        tf_ups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_upsActionPerformed(evt);
            }
        });

        tf_impresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_impresoraActionPerformed(evt);
            }
        });

        tf_laptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_laptopActionPerformed(evt);
            }
        });

        tf_bulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bultoActionPerformed(evt);
            }
        });

        tf_cargador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cargadorActionPerformed(evt);
            }
        });

        tf_modem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_modemActionPerformed(evt);
            }
        });

        tf_internet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_internetActionPerformed(evt);
            }
        });

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaInventario);

        btn_enviar.setText("Guardar");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        btn_tablaOpen.setText("Mostrar tabla");
        btn_tablaOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tablaOpenActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_tablaOpen2.setText("Actualizar");
        btn_tablaOpen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tablaOpen2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_enviar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_tablaOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tablaOpen2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enviar)
                    .addComponent(btn_tablaOpen)
                    .addComponent(btn_modificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_tablaOpen2)))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Serial");

        tf_serial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_serialActionPerformed(evt);
            }
        });

        tf_buscar_RC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_buscar_RCActionPerformed(evt);
            }
        });
        tf_buscar_RC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_buscar_RCKeyPressed(evt);
            }
        });

        bt_buscar_RC.setText("Buscar");
        bt_buscar_RC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscar_RCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(box_filtro_RC, 0, 204, Short.MAX_VALUE)
                    .addComponent(tf_buscar_RC))
                .addGap(18, 18, 18)
                .addComponent(bt_buscar_RC, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box_filtro_RC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_buscar_RC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_buscar_RC))
                .addContainerGap())
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemamigue/gemapng2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_monitor, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_teclado, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_centro, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_zona, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_mouse, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_modem, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_internet, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_cargador, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_laptop, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_bulto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_impresora, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_ups, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_serial, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_centro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_zona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_mouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_monitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_teclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tf_impresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(tf_laptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(tf_bulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_cargador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tf_modem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tf_internet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_ups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tf_serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_centroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_centroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_centroActionPerformed

    private void tf_zonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_zonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_zonaActionPerformed

    private void tf_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cpuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cpuActionPerformed

    private void tf_mouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_mouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_mouseActionPerformed

    private void tf_monitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_monitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_monitorActionPerformed

    private void tf_tecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tecladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tecladoActionPerformed

    private void tf_upsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_upsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_upsActionPerformed

    private void tf_impresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_impresoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_impresoraActionPerformed

    private void tf_laptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_laptopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_laptopActionPerformed

    private void tf_bultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bultoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bultoActionPerformed

    private void tf_cargadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cargadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cargadorActionPerformed

    private void tf_modemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_modemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_modemActionPerformed

    private void tf_internetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_internetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_internetActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        // TODO add your handling code here:
        if(tf_centro.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "El Centro no puede estar vacio!");
        }else{
            insertarDatos();            
        }
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_tablaOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tablaOpenActionPerformed
        // TODO add your handling code here:
        mostraTabla("");
    }//GEN-LAST:event_btn_tablaOpenActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        modificarDatos();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_tablaOpen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tablaOpen2ActionPerformed
        // TODO add your handling code here:
        actualizarDatos();
    }//GEN-LAST:event_btn_tablaOpen2ActionPerformed

    private void tf_buscar_RCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_buscar_RCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_buscar_RCActionPerformed

    private void tf_serialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_serialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_serialActionPerformed

    private void bt_buscar_RCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscar_RCActionPerformed
        // TODO add your handling code here:
        buscarTFconBOX();
    }//GEN-LAST:event_bt_buscar_RCActionPerformed

    private void tf_buscar_RCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscar_RCKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarTFconBOX();
            tf_buscar_RC.setText("");
        }
    }//GEN-LAST:event_tf_buscar_RCKeyPressed

                //eliminar datos
    private void eliminar() {
        int fila = tablaInventario.getSelectedRow();
        String valor = tablaInventario.getValueAt(fila, 0).toString();

        if (fila >= 0) {
            try {
                PreparedStatement pps = cn.prepareStatement("DELETE FROM Inventario WHERE  Id = '" + valor + "'");
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Dato eliminado");
                mostraTabla("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al eliminar el dato");
                Logger.getLogger(MenuMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fila no seleccionada");
            
        }
    }

        //mostra la tabla
        private void mostraTabla(String valor){
         DefaultTableModel modelo = new DefaultTableModel();
            //agregar columnas
            modelo.addColumn("Id");
            modelo.addColumn("Centro");
            modelo.addColumn("Zona");
            modelo.addColumn("CPU");
            modelo.addColumn("Mouse");
            modelo.addColumn("Monitor");
            modelo.addColumn("Teclado");
            modelo.addColumn("UPS");
            modelo.addColumn("Impresora");
            modelo.addColumn("Laptop");
            modelo.addColumn("Bulto");
            modelo.addColumn("Cargador");
            modelo.addColumn("Modem USB");
            modelo.addColumn("Internet");
            modelo.addColumn("Serial");
            tablaInventario.setModel(modelo);
            //Fin
            
            //variables
            String sql = "";
            //fin
            
            //verificar que es SQL
            if(valor.equalsIgnoreCase("")){
                sql = "SELECT * FROM Inventario";
            }else{
                sql = "SELECT * FROM Inventario WHERE " +atributo +"=" +"'" +valor +"'";
            }
            //fin


            String datos[] = new String[16];
            Statement st;
            
             try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            

            
            //Agregar los reglones
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                datos[9] = rs.getString(10);
                datos[10] = rs.getString(11);
                datos[11] = rs.getString(12);
                datos[12] = rs.getString(13);
                datos[13] = rs.getString(14);
                datos[14] = rs.getString(15);
                modelo.addRow(datos);
            }
            
            tablaInventario.setModel(modelo);
            //Fin

           
            
            //Fin
        } catch (SQLException ex) {
            Logger.getLogger(MenuMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
                //enviar los datos a la base de datos
    private void insertarDatos() {
       // if (probarCamposVacios() == true) {
            //pasarTFaVariables();
            try {
                PreparedStatement ppt = cn.prepareStatement("INSERT INTO Inventario(Centro, Zona, CPU, Mouse, Monitor, Teclado, UPS, Impresora, Laptop, Bulto, Cargador, ModemUSB, Internet, Serial) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                //ppt.setString(1, tf_idproducto_RC.getText());
                ppt.setString(1, tf_centro.getText());
                ppt.setInt(2, Integer.parseInt(tf_zona.getText()));
                ppt.setInt(3, Integer.parseInt(tf_cpu.getText()));
                ppt.setInt(4, Integer.parseInt(tf_mouse.getText()));
                ppt.setInt(5, Integer.parseInt(tf_monitor.getText()));
                ppt.setInt(6, Integer.parseInt(tf_teclado.getText()));
                ppt.setInt(7, Integer.parseInt(tf_ups.getText()));
                ppt.setInt(8, Integer.parseInt(tf_impresora.getText()));
                ppt.setInt(9, Integer.parseInt(tf_laptop.getText()));
                ppt.setInt(10, Integer.parseInt(tf_bulto.getText()));
                ppt.setInt(11, Integer.parseInt(tf_cargador.getText()));
                ppt.setInt(12, Integer.parseInt(tf_modem.getText()));
                ppt.setString(13, tf_internet.getText());
                ppt.setString(14, tf_serial.getText());
     
                ppt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Hubo un error al insertar los datos", "Problema con los datos", JOptionPane.QUESTION_MESSAGE);
                Logger.getLogger(MenuMain.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
        //modificar datos
    private void modificarDatos() {
        int fila = tablaInventario.getSelectedRow();
        if (fila >= 0) {
            tf_centro.setText(tablaInventario.getValueAt(fila, 1).toString());
            tf_zona.setText(tablaInventario.getValueAt(fila, 2).toString());
            tf_cpu.setText(tablaInventario.getValueAt(fila, 3).toString());
            tf_mouse.setText(tablaInventario.getValueAt(fila, 4).toString());
            tf_monitor.setText(tablaInventario.getValueAt(fila, 5).toString());
            tf_teclado.setText(tablaInventario.getValueAt(fila, 6).toString());
            tf_ups.setText(tablaInventario.getValueAt(fila, 7).toString());
            tf_impresora.setText(tablaInventario.getValueAt(fila, 8).toString());
            tf_laptop.setText(tablaInventario.getValueAt(fila, 9).toString());
            tf_bulto.setText(tablaInventario.getValueAt(fila, 10).toString());
            tf_cargador.setText(tablaInventario.getValueAt(fila, 11).toString());
            tf_modem.setText(tablaInventario.getValueAt(fila, 12).toString());
            tf_internet.setText(tablaInventario.getValueAt(fila, 13).toString());
            tf_serial.setText(tablaInventario.getValueAt(fila, 14).toString());
                        //para que se pueda modificar el id del usuario
            tf_buscar_RC.setText(tablaInventario.getValueAt(fila, 0).toString());

        } else {
            JOptionPane.showMessageDialog(null, "Fila no seleccionada", "Desconocido", 3);
        }
    }
    
        //actualizar datos
    private void actualizarDatos() {
        //"(Centro, Zona, CPU, Mouse, Monitor, Teclado, UPS, Impresora, Laptop, Bulto, Cargador, ModemUSB, Internet)"
                
        try {
            PreparedStatement pps = cn.prepareStatement("UPDATE Inventario SET Centro = '" + tf_centro.getText()
                    + "',Zona = '"
                            + Integer.parseInt(tf_zona.getText())
                    +"', CPU = '"
                            +Integer.parseInt(tf_cpu.getText())
                    + "',Mouse = '"
                            + Integer.parseInt(tf_mouse.getText())
                    + "',Monitor = '"
                            +Integer.parseInt(tf_monitor.getText())
                    + "',Teclado = '"
                            +Integer.parseInt(tf_teclado.getText())
                    + "',UPS = '"
                            +Integer.parseInt(tf_ups.getText())
                    + "',Impresora = '"
                            +Integer.parseInt(tf_impresora.getText())
                    + "',Laptop = '"
                            +Integer.parseInt(tf_laptop.getText())
                    + "',Bulto = '"
                            +Integer.parseInt(tf_bulto.getText())
                    + "',Cargador = '"
                            +Integer.parseInt(tf_cargador.getText())
                    + "',ModemUSB = '"
                            +Integer.parseInt(tf_modem.getText())
                    + "',Internet = '"
                            +Integer.parseInt(tf_internet.getText())
                    + "',Serial = '"
                            +Integer.parseInt(tf_serial.getText())
                    
                    + "' WHERE Id = '"
                            + tf_buscar_RC.getText() +"'");
            pps.executeUpdate();
 
            JOptionPane.showMessageDialog(null, "Datos actualizados");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ha cometido algun error");
            Logger.getLogger(MenuMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Metodo para inicalizar datos
    private void EnviarNumeros(){
        tf_bulto.setText("0");
        tf_cargador.setText("0");
        //tf_centro.setText("0");
        tf_cpu.setText("0");
        tf_impresora.setText("0");
        tf_internet.setText("0");
        tf_laptop.setText("0");
        tf_modem.setText("0");
        tf_monitor.setText("0");
        tf_mouse.setText("0");
        tf_teclado.setText("0");
        tf_ups.setText("0");
        tf_zona.setText("0");
        tf_serial.setText("0");
    }
    
            //llenar el combo box del buscar
    private void llenarBox(){
        box_filtro_RC.addItem("Centro");
        box_filtro_RC.addItem("Zona");
        box_filtro_RC.addItem("Serial");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_filtro_RC;
    private javax.swing.JButton bt_buscar_RC;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_tablaOpen;
    private javax.swing.JButton btn_tablaOpen2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField tf_bulto;
    private javax.swing.JTextField tf_buscar_RC;
    private javax.swing.JTextField tf_cargador;
    private javax.swing.JTextField tf_centro;
    private javax.swing.JTextField tf_cpu;
    private javax.swing.JTextField tf_impresora;
    private javax.swing.JTextField tf_internet;
    private javax.swing.JTextField tf_laptop;
    private javax.swing.JTextField tf_modem;
    private javax.swing.JTextField tf_monitor;
    private javax.swing.JTextField tf_mouse;
    private javax.swing.JTextField tf_serial;
    private javax.swing.JTextField tf_teclado;
    private javax.swing.JTextField tf_ups;
    private javax.swing.JTextField tf_zona;
    // End of variables declaration//GEN-END:variables
}
